# Extract and compile translations for all PRs.

name: 'Extract and compile translations'

on:
  workflow_call:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  extract_translations:
    name: Extract and compile translations
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ./.github/actions/node-install

      - name: Extract and compile translations
        run: |
          npm run translate:extract
          npm run translate:compile

      - name: Check and commit any files created
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@documenso.com'
          git add packages/lib/translations
          git diff --staged --quiet --exit-code || (git commit -m "chore: extract translations" && git push)
